# Generated by Django 5.1.4 on 2025-01-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_buyer_current_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='current_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
