# Generated by Django 5.1.4 on 2025-01-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
